services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: casbin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - casbin_server-network
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  casbin_server-network:
    driver: bridge

volumes:
  postgres_data:
    external: false